version: '3.9'

services:
  web:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./src:/var/www/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app

  app:
    image: php:8.3-fpm-alpine
    volumes:
      - ./src:/var/www/html
